version: 2
jobs:
  build:
    docker:
      - image: miroslawmajka/microsoft-node
    steps:
        - checkout
        - run:
            name: Restore Packages
            command:
                dotnet restore
        - run:
            name: Build Solution
            command:
                dotnet build
        - run: mkdir output
        - run: cp Environments/local-headless-chrome.env .env
        - run: npm install -g sample-express-app
        # TODO: run the web app and test using chromedriver binary
        #- run:
        #    name: Start Sample Express App in the background and run Selenium tests
        #    command: (sample-express-app > output/express.log &) && dotnet test
        # TODO: get test results and store
        #- store_artifacts:
        #    path: output
