version: 2
jobs:
  build:
    docker:
      - image: miroslawmajka/microsoft-node
    steps:
        - checkout
        - run:
            name: Restore Packages
            command:
                dotnet restore
        - run:
            name: Build Solution
            command:
                dotnet build
        - run: cp Environments/local-headless-chrome.env .env
        - run: npm install -g sample-express-app
        - run:
            name: Start Sample Express App in the background and run Selenium tests
            command: (sample-express-app > express.log &) && dotnet test
